### ISSUE TITLE
Readme might need updated pear instructions

### ISSUE THREAD

**Issue by Mitch-Twilio** [twilio/twilio-php#210]
$ pear channel-discover twilio-pear.herokuapp.com/pear might be deprecated? Should the channel-discover be pear channel-discover twilio.github.com/pear?

**Comment by skimbrel** [comment]
Yeaaah and I swear we already did this. Let me dig through the git branches to see if there’s something unmerged somewhere.

**Comment by alexcchan** [comment]
FYI http://twilio-pear.herokuapp.com/pear/channel.xml is returning HTTP 500

**Comment by ecaron** [comment]
Maybe this could be closed? Because in https://github.com/twilio/twilio-php/commit/18147285d4fd2a48f88126394c90c6da71a14066 reference to the pear installation was removed altogether (probably a good thing, and there are [lots of good articles explaining why](http://fabien.potencier.org/article/72/the-rise-of-composer-and-the-fall-of-pear))

**Comment by skimbrel** [comment]
Pear is dead, long live composer and Packagist.
