### ISSUE TITLE
Error when sending SMS

### ISSUE THREAD

**Issue by gabgrullon** [twilio/twilio-php#211]
Guys:
im very new on Twilio...Im download the library to my project folder. Also I created the PHP to launch the SMS, but Im getting an error...Can somebody explain me what Im doing wrong???
Thanks,
Gabriel

![screen shot 01-17-15 at 11 13 am](https://cloud.githubusercontent.com/assets/10574790/5789501/61c8daea-9e3b-11e4-8924-90d4d1334ea9.PNG)
![screen shot 01-17-15 at 11 12 am 001](https://cloud.githubusercontent.com/assets/10574790/5789503/63ee9846-9e3b-11e4-8f16-f0a241e67c41.PNG)
![error](https://cloud.githubusercontent.com/assets/10574790/5789510/ae69970e-9e3b-11e4-8d8a-ba95346d64c5.jpg)

**Comment by Gipetto** [comment]
You've followed the examples a little TOO closely. Your script cannot find the library because your `require` statement for the library is placeholder text from the sample code.

On line 9 of your `SMS_Send.php` file your path needs to be `twilio-php/Services/Twilio.php`. The paths supplied to `include` and `require` statements can be full paths or relative. You can get more information on that here: http://php.net/manual/en/function.include.php

**Comment by gabgrullon** [comment]
thanks Shawn..Now I obviously passed to twilio.php, as you can see on attachement..Now is giving me an error on line 15 and 47 on Twilio.php script..Line 15 says: return include dirname(__FILE__) . "/$file.php";
Line 47 says: protected $retryAttempts;
Sorry, as Im very new in PHP...

Regards, 

Gabriel F. Grullón 
(786) 270-6946



Date: Sat, 17 Jan 2015 10:30:20 -0800

**Comment by skimbrel** [comment]
Hi! This repo isn't always monitored closely — if you need help using the library please email help@twilio.com. Our Support team is familiar with all of the helper libraries and will usually respond within a day.
