### ISSUE TITLE
Tracking Conversaions

### ISSUE THREAD

**Issue by peardox** [twilio/twilio-php#250]
I can't find any reference to setting cookie tracking for messages / calls

Should be easy enough to add

**Comment by philnash** [comment]
Sorry for the slow response on this.

You can set cookies on any incoming call or message webhooks. There's more documentation on this about messages than calls, so that's the best place to look. Here's some bits to get you started:

Help page on how cookies work with Twilio: https://www.twilio.com/help/faq/twilio-basics/how-do-twilio-cookies-work
Documentation on setting cookies on incoming messages: https://www.twilio.com/docs/api/twiml/sms/your_response#cookies
Quickstart guide on conversation tracking: https://www.twilio.com/docs/quickstart/php/sms/tracking-conversations
Blog post guide on conversation tracking (though this uses python): https://www.twilio.com/blog/2014/07/the-definitive-guide-to-sms-conversation-tracking.html

Let me know if that helps at all.

**Comment by peardox** [comment]
A pretty empty answer follows as I've read all that stuff already

I want to both be helpful and have modest income (someone pays me, I denote to GitHub)

Don't worry, you're not the only platform I'm trying to fix (try Heroku on PHP with a long job)

I'll feed back in as much as I can.

I guess the best idea is a doofer (two in one)

Specific issues are Heroku (forced on me) not having threads and twilio-php not being a full lib

Everything has a solution - my boss gets upset when I try to fix things (looks like I'm not working on his stuff) - actually, bossman is cool with most decisions I make
