### ISSUE TITLE
Can't send any request with test credentials

### ISSUE THREAD

**Issue by reyhansofian** [twilio/twilio-php#251]
I'm trying to send SMS using my test credentials. My code looks like on [API Explorer](https://www.twilio.com/user/account/developer-tools/api-explorer/message-create)
```
// this line loads the library 
require('/path/to/twilio-php/Services/Twilio.php'); 
 
$account_sid = 'AC26c0bcee095a9a889a171666786fc857'; 
$auth_token = '[AuthToken]'; 
$client = new Services_Twilio($account_sid, $auth_token); 
 
$client->account->messages->create(array( 
	'To' => "+xx788363xxx", 
	'From' => "+14695187643", 
	'Body' => "test",  
```
But I got this on my PHP error log
```
PHP message: Could not decode response body as JSON. This likely indicates a 500 server error
```

After trying with POSTMAN, it says
```
{
  "code": 21606,
  "message": "The From phone number +14695187643 is not a valid, SMS-capable inbound phone number or short code for your account.",
  "more_info": "https://www.twilio.com/docs/errors/21606",
  "status": 400
}
```
So, I'm trying using my live credential. And everything is fine.

**Comment by reyhansofian** [comment]
Also, I'm trying to create request based on [docs](https://www.twilio.com/docs/api/rest/request) via Postman using test credentials. The URL looks like
```
https://{AccountSid}:{AuthToken}@api.twilio.com/2010-04-01/Accounts
```
And I got this response
```
<?xml version='1.0' encoding='UTF-8'?>
<TwilioResponse>
    <RestException>
        <Code>20008</Code>
        <Message>Resource not accessible with Test Account Credentials</Message>
        <MoreInfo>https://www.twilio.com/docs/errors/20008</MoreInfo>
        <Status>403</Status>
    </RestException>
</TwilioResponse>
```

**Comment by philnash** [comment]
Hi @reyhansofian,

I'm afraid that's expected behaviour. The [test credentials only work for 3 of the API endpoints](https://www.twilio.com/docs/api/rest/test-credentials#supported-resources), and the SMS endpoint, [SMS/Messages](https://www.twilio.com/docs/api/rest/sms), is deprecated in favour of the [Messages](https://www.twilio.com/docs/api/rest/message) endpoint. It's best to test using your real credentials.

Let me know if this helps!

**Comment by reyhansofian** [comment]
@philnash 

You're right. Sorry for my stupidity. This [FAQ page](https://www.twilio.com/help/faq/twilio-basics/how-does-twilios-free-trial-work) said that I won't be charged on trial account even if I'm using live credentials.

**Comment by cfh463** [comment]
@philnash you should have the documentation on the Test Credentials page reflect the proper URL not SMS/Messages - I tripped up on this as well.

**Comment by philnash** [comment]
@cfh463 You're absolutely right, I'll look into this.

**Comment by bjones6** [comment]
Just want to point out I ran into this problem today while writing some load-balancing-esque tests with the twilio-node library. It's important to us that we know we can handle throughput at our end, and the easiest way to do this is to get as close as possible to the real API call. Am I correct to understand I can't make API calls to send mock text messages with my test credentials counter to what the docs say? I'm afraid these tests run too frequently and at too high a volume to be practically done with our live credentials.

Would love to know if there are any hacks to achieve this, otherwise I'm just going to mix live credential usage and setTimeout(500) for now.

By the way we're across the hall at Hatch Today and apart from this our Twilio integrations have been a joy.

**Comment by philnash** [comment]
@bjones6 I would not recommend running any automated tests against external services. If you do need to test, particularly stress test, like that, I would stand up your own clone of the Twilio API to run your application against. That way you can control how it acts within your tests and it doesn't cost you on the Twilio end.

I am following up with the API team to see what we can do about this resource and its documentation. I hope to bring news of that soon.
