### ISSUE TITLE
$this behaviour changed from 5.3php to 5.6php?

### ISSUE THREAD

**Issue by elpeyotl** [twilio/twilio-php#294]
According to the problem I had[ here](http://stackoverflow.com/questions/35778981/twilio-php-connector-cant-echo-twillio-answer/35779385#35779385), I open this issue:

We found out that the $this behaviour changed from php 5.3 to php 5.6.  How $this responds to foreach. So this could be that [this](https://github.com/twilio/twilio-php/blob/3ec47c0bf8bce1a25e02e007c1245405bdadb7a6/Services/Twilio/Resource.php#L123-L131) code will not work anymore. 

Can please someone check?

**Comment by ihumanable** [comment]
Looked into this, the behavior of `$this` in a foreach loop did not change between 5.3 and 5.6.  I'm able to reproduce the issue in the link with php 5.5 and can echo normally in php 5.3, debugging it reveals the following.

The fatal error is caused by `__toString()` not returning a string.  It instead returns the boolean value `FALSE`.  It does this because of `json_encode_error` #6 Recursion detected.  Why does this happen?It's because in executing `echo($client);` causes PHP to call the `__toString()` method on the client.  The `__toString()` method then iterates over all the keys and creates an array to `json_encode`.  Two of these keys (`account` and `accounts`) have back references to the `$client`.  When `json_encode` attempts to encode this value it detects that its caught in a recursive loop and gives up returning a `FALSE`.  You can verify this by checking the `json_last_error` and `json_last_error_msg` functions.

The major difference between 5.3 and new versions of PHP is that in 5.3 `json_encode` used to just raise a warning (which you can easily ignore) and would turn the recursive value into a `null`.  As of PHP 5.4.0 (probably because of this bugfix https://bugs.php.net/bug.php?id=61537) this behavior changed so that `json_encode` returns FALSE and sets the appropriate error codes and messages.

The constant `JSON_PARTIAL_OUTPUT_ON_ERROR` was added in PHP 5.5.0 to support this particular use case, as noteed here http://php.net/manual/en/json.constants.php#constant.json-error-recursion.

I tried updating the library to use the `JSON_PARTIAL_OUTPUT_ON_ERROR` flag but it still resulted in `FALSE` being returned from `json_encode`.  Since `JSON_PARTIAL_OUTPUT_ON_ERROR` was not introduced until 5.5.0 and the 4.x line supports down to 5.2 I can not add this even if it had fixed the problem.

Best solution is to not print the $client object, it is not meant to be printable and doesn't contain useful information as to the response.
