### ISSUE TITLE
Custom sender number to title

### ISSUE THREAD

**Issue by theavuthnhel** [twilio/twilio-php#306]
*Note: These issues are for bugs and feature requests for the helper libraries. If you need help or support, please email help@twilio.com and one of our experts will assist you!*

**Version:**
**API Subdomain (api/taskrouter/ip_messaging):**

### Code Snippet
```php
# paste code here
require "/path/to/twilio-php/Services/Twilio.php";

$AccountSid = "{{ account_sid }}"; // Your Account SID from www.twilio.com/console
$AuthToken = "{{ auth_token }}";   // Your Auth Token from www.twilio.com/console

$client = new Services_Twilio($AccountSid, $AuthToken);

try {
    $message = $client->account->messages->create(array(
        "From" => ["+12345678901" => "Sender"], // From a valid Twilio number
        "To" => "+12345678901", // Text this number
        "Body" => "Hello from PHP",
    ));
} catch (Services_Twilio_RestException $e) {
    echo $e->getMessage();
}
```

### Exception / Log
```
<place exception / log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by ihumanable** [comment]
If I'm not mistaken, I believe you are requesting to be able to set a custom name on a text message instead of having it show up as the Twilio Phone Number.

There is partial support for this in the API via OutgoingCallerIds and Alphanumeric Sender IDs. This does not require a change to the Helper Library.

More information can be found here: https://www.twilio.com/help/faq/sms/can-i-specify-the-phone-number-a-recipient-sees-when-getting-an-sms-from-my-twilio-app
