### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException

### ISSUE THREAD

**Issue by evgenivanov90** [twilio/twilio-php#343]
Hi! can you help me to understand why this "Allowed memory size of 536870912 bytes exhausted (tried to allocate 59002 bytes)" problem cause? I've run the code for sending messages in cron.

**Comment by ihumanable** [comment]
Generally this PHP Error indicates that you have a memory leak somewhere.  Long running scripts can have this issue occur, but this error does not seem to be caused by the `twilio-php` helper library.

If you investigate the error and believe there to be a memory leak in the `twilio-php` library please reopen this issue.
