### ISSUE TITLE
Blog Resources give wrong information.

### ISSUE THREAD

**Issue by chriscalip** [twilio/twilio-php#372]
It looks like a time sink for devs checking out twilio.
This blog
https://www.twilio.com/blog/2016/03/how-to-validate-phone-numbers-in-php-with-the-twilio-lookup-api.html
contains deprecated information.

**Comment by philnash** [comment]
Hi @chriscalip,

You're right, this blog post uses version 4 of the helper library and the latest is now version 5. We are taking steps to make this more explicit in our old posts so that you don't get caught out like this.

In the meantime, you can see more [examples of using the Lookup API in the documentation](https://www.twilio.com/docs/api/lookups#examples) which covers both the v4 and v5 PHP helper library.

Thanks for reporting this!
