### ISSUE TITLE
Why not have InstanceResource have toArray()

### ISSUE THREAD

**Issue by johnpaulmedina** [twilio/twilio-php#381]
Is there a reason to protect the properties of lets say a CallInstance? Why not have the option for toArray() so that the instance can be just outputted as an associative array. Does this pose some sort of vulnerability?

I would like to have the ability to fetch any instance and just call ->toArray() and see that properties as is.

```
public function toArray() {
     return $this->properties;
}
```

That should output like so:

```
array:25 [▼
  "accountSid" => "ACa1234567890"
  "annotation" => null
  "answeredBy" => null
  "apiVersion" => "2010-04-01"
  "callerName" => ""
  "dateCreated" => DateTime {#1278 ▶}
  "dateUpdated" => DateTime {#1279 ▶}
  "direction" => "outbound-api"
  "duration" => "22"
  "endTime" => DateTime {#1280 ▶}
  "forwardedFrom" => null
  "from" => "+xxxxxxx"
  "fromFormatted" => "xxxxxx"
  "groupSid" => null
  "parentCallSid" => null
  "phoneNumberSid" => "xxxxxxxx"
  "price" => "-0.01500"
  "priceUnit" => "USD"
  "sid" => "xxxxxx"
  "startTime" => DateTime {#1281 ▶}
  "status" => "completed"
  "subresourceUris" => array:2 [▶]
  "to" => "xxxxx"
  "toFormatted" => "(xxxxxx"
  "uri" => "/2010-04-01/Accounts/ACa1234567890/Calls/xxxxxx.json"
]

```

**Comment by ihumanable** [comment]
@johnpaulmedina Thank you for your feedback.  There is no vulnerability reason to mark the `$properties` field as `protected`.  It was marked as `protected` because the internal `$properties` field is an implementation detail that might change in the future. 

Beyond that, your suggestion of having an `InstanceResource::toArray()` method seems like a good one that I see no issue with.  I will update our library to provide this facility and update this ticket once it has been merged / released.

**Comment by johnpaulmedina** [comment]
@ihumanable Great thanks. I can do a pull request? Also I am assuming the only reason that was not put in this version is because you are keeping the "instance" through the proxy to modify? Just curious. 

I will make a pull request now so that you can merge.

**Comment by ihumanable** [comment]
@johnpaulmedina didn't see that you were putting together a PR, I've put one together here https://github.com/twilio/twilio-php/pull/382 if you could provide a review.

**Comment by johnpaulmedina** [comment]
Yep! Thanks!

**Comment by ihumanable** [comment]
I will merge this and release as `twilio-php 5.4.2` I will close out this ticket once the new version is available in packagist.

**Comment by ihumanable** [comment]
Thank you for helping make our library better 😄

**Comment by johnpaulmedina** [comment]
Just to confirm that version is the alpha? If I were to pull it that will have the merge?

**Comment by ihumanable** [comment]
`master` and `alpha` have been updated with this change, you can find artifacts standard artifact as `5.4.2` on packagist, if you need an alpha artifact, the new alpha has been published as `5.4.2-alpha1`  Documentation on http://twilio.github.io/twilio-php has been updated.

Version `5.4.2` is the latest library now and is fully supported by Twilio.

**Comment by johnpaulmedina** [comment]
Some what of an issue just ran into.

```
public function read($options = array(), $limit = null, $pageSize = Values::NONE) {
        return iterator_to_array($this->stream($options, $limit, $pageSize), false);
    }
```

When you call something like so 
```
 $recordings = $this->client->calls($callsid)->fetch()->recordings->read();
```

Since the read function `return iterator_to_Array` its seems that calling `toArray()` will throw an error saying calling toArray on array.

Just a thought for future update maybe when dealing with multiple items or collection of Instances when calling toArray() if it is array than it will call toArray on each subsequent InstanceResource.

**Comment by ihumanable** [comment]
@johnpaulmedina thanks for the feedback, we will consider that for a future update, for now we thought it would be better to have read return a standard `array()` instance because all PHP developers would be familiar with how `array()` works and could utilize the `array_*` family of functions.

I will keep the Laravel style collections in mind as a future enhancement.

**Comment by johnpaulmedina** [comment]
Maybe a start ? #383

**Comment by ihumanable** [comment]
Commented just as you opened the PR 😆 , let me take a look.

**Comment by johnpaulmedina** [comment]
I can expand on the TwilioCollection later like adding support for iteration and things. Port concepts from the laravel collection.

**Comment by ihumanable** [comment]
If you are using Laravel, would it be better to take the array returned from `read` and pass it into an [Illuminate\Support\Collection](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Support/Collection.php)?

I wouldn't want to have to try to keep parity with Laravel, which is a large and fantastic project.  Also if someone is comfortable with some other Collection library in PHP, having our library stay agnostic of the collection allows people to use whichever array wrapper they are most comfortable with.

Maybe instead of providing a Collection abstraction, we could instead allow you to register a Collection class that we would wrap the array with?

Only problem would be, for Laravel at least, that `InstanceResource` does not implement `Arrayable` even though it duck types the interface.

**Comment by johnpaulmedina** [comment]
The other issue is calling the subsequent `toArray()` methods. I completely agree with the mindset because what I am doing is essentially using the `collect` function once its flattened out. 

However, allowing to bring in a collection is nice but making the Twilio-PHP self sufficient would also be a nice thing. I want to plug in the SDK and be able to use it without having too much clutter as I am sure other developers would feel. 

Having a collection built-in will allow me to iterate and show items quickly without expanding on the SDK or wrapping it inside of a framework. 

Just my thought.

**Comment by johnpaulmedina** [comment]
I must have skimmed over the part you said abstraction. I see what you are saying here. Maybe a CollectionWrapper could do the trick. Ill give this some more thought.
