### ISSUE TITLE
Random PHP Notice: Undefined index "Beta"

### ISSUE THREAD

**Issue by georaldc** [twilio/twilio-php#389]
Occurs when accessing certain endpoints that return a payload array that's supposed to always include a "beta" key (IncomingPhoneNumberInstance class for instance). Is this some sort of throttling side effect, because I can get it to happen after a couple of consecutive calls?

The api explorer exhibits the same behavior of sometimes dropping off the "beta" key from the response returned

**Comment by ihumanable** [comment]
This would have been the behavior seen during this [REST API Incident Event](https://status.twilio.com/incidents/pk1p0ccpg5wy).

On 2016-11-21 for a brief period from 02:03UTC to 02:38UTC there was a 5% chance that some fields would be dropped due to a issue in our Feature Gating System.  The symptoms you describe (and the timeframe of this issue) line up.

With any Incident that impacts our users, we performed an internal post-mortem to understand the root cause and are implementing several betterments to prevent this issue from recurring in the future.  95% of requests continued to be handled correctly as the system automatically failed over correctly for the majority of requests.  This is why it seemed to be happening intermittently.

I'm sorry that you were affected by this Incident, it is not expected behavior and the Helper Library couldn't understand the incorrect responses.  Along with our server-side system betterments, I will reopen our incident to see if there should be betterments added to the Helper Libraries to more gracefully handle malformed responses. 

Thank you for reporting this issue, apologies again for any issues this caused you.

If you would like further information, you can contact [help@twilio.com](mailto:help@twilio.com) and reference this issue.
