### ISSUE TITLE
How to access only response object in php 

### ISSUE THREAD

**Issue by ihatecodinglikeking** [twilio/twilio-php#428]
Hi There, 

I just started using Twilio in my php application 

when I tried to use fetch call details by sid its working fine but only its giving one object 

like `$call = $client->calls("CA42ed11f93dc08b952027ffbc406d0868")->fetch();`
`echo $call->to;`

now its giving to number but I want entire object like 
`{
	"sid": "CAe1644a7eed5088b159577c5802d8be38",
	"date_created": "Tue, 10 Aug 2010 08:02:17 +0000",
	"date_updated": "Tue, 10 Aug 2010 08:02:47 +0000",
	"parent_call_sid": null,
	"account_sid": "AC5672ab7979a713bf058e3a0ac5789104",
	"to": "+14153855708",
	"from": "+14158141819",
	"phone_number_sid": null,
	"status": "completed",
	"start_time": "Tue, 10 Aug 2010 08:02:31 +0000",
	"end_time": "Tue, 10 Aug 2010 08:02:47 +0000",
	"duration": "16",
	"price": "-0.03000",
	"direction": "outbound-api",
	"answered_by": null,
	"api_version": "2008-08-01",
	"forwarded_from": null,
	"caller_name": null,
	"uri": "\/2010-04-01\/Accounts\/AC5672ab7979a713bf058e3a0ac5789104\/Calls\/CAe1644a7eed5088b159577c5802d8be38.json",
	"subresource_uris":{
		"notifications": "\/2010-04-01\/Accounts\/AC5672ab7979a713bf058e3a0ac5789104\/Calls\/CAe1644a7eed5088b159577c5802d8be38\/Notifications.json",
		"recordings": "\/2010-04-01\/Accounts\/AC5672ab7979a713bf058e3a0ac5789104\/Calls\/CAe1644a7eed5088b159577c5802d8be38\/Recordings.json"
	}
}`

so I tired to return $call  but its giving like all protected objects stuff, I just need only
`[properties:protected] => Array
        ( )` 
so how can i access it

**Comment by jmctwilio** [comment]
All of the values noted above should have accessors on the `$call` object.  The key difference is that they are accessed in camelCase rather than snake_case.

As a rule, the library marks data as protected when it is used internally in the library and subject to change.  Building an application which uses protected data could introduce a lot of risk.  Also, you will have a strong dependency on a particular state/version of the library and API.

The `$call` object you have has these members: {sid, dateCreated, dateUpdated, parentCallSid, accountSid, groupSid, annotation, to, toFormatted, from, fromFormatted, phoneNumberSid, status, startTime, endTime, duration, price, priceUnit, direction, answeredBy, apiVersion, forwardedFrom, callerName, uri, subresourceUris, recordings}.

If you just need to inspect the data in the object, you should be able to use `var_dump($call);` -- that shows everything along with it's accessibility.  Please let me know if this doesn't help.
