### ISSUE TITLE
[Question] Removal of dev alpha branch

### ISSUE THREAD

**Issue by joshhornby** [twilio/twilio-php#441]
Hi,

In our application we were reliant on the `dev-alpha` branch of this package, as we are using Sync.

I see that this branch has been deleted and searching for Sync (https://github.com/twilio/twilio-php/search?utf8=%E2%9C%93&q=sync&type=) shows none of the code that powered Sync is in this repo. Can I ask what the official line of using Sync with `twilio-php` is? What's the migration path from `dev-alpha` back to a stable release?

Thanks

**Comment by dougblack** [comment]
Hey @joshhornby you've caught us mid rollout of an architectural change in the libraries. We're rolling the `alpha` branch into the regular `master` artifact, effectively putting all Twilio products in `master` and obviating the need for `alpha`. We actually haven't yet done this migration, but we have already deleted the `alpha` branch. In the meantime if you need to reference a git object for your build, tag `5.12.1-alpha1` should suffice.

In general, we recommend referencing actual releases, not git branches. We can't provide any SLA around branches a) always existing and b) having code that passes tests. Releases will satisfy both of these constraints, which is why updating your code to point to `5.12.1-alpha` is a fix here.

**Comment by joshhornby** [comment]
Hi @dougblack 

Sounds good to me, thanks for the response.
