### ISSUE TITLE
CURL test send a SMS message not working 

### ISSUE THREAD

**Issue by ducho** [twilio/twilio-php#609]
### Issue Summary
Your guide with test examples does not working
https://www.twilio.com/docs/sms/send-messages?code-sample=code-send-an-mms-message&code-language=curl&code-sdk-version=json

### Code Snippet
```
DSs-MacBook-Pro:~ ducho$ curl -X POST https://api.twilio.com/2010-04-01/Accounts/AC7ccbc7e29f1d9919cda359566f86c70d/Messages.json --data-urlencode "Body=All in the game, yo" --data-urlencode "From=MOJHOSTING” \
--data-urlencode "To=+421950281832” -u AC7ccbc7e29f1d9919cda359566f86c70d:my_auth_token
```

### Exception/Log
```
{"code": 21604, "message": "A 'To' phone number is required.", "more_info": "https://www.twilio.com/docs/errors/21604", "status": 400}
```

### Technical details:
* twilio-php version:
* php version:

**Comment by childish-sambino** [comment]
The `From` number needs to be a properly formatted number. The error is misleading.

**Comment by ducho** [comment]
> The `From` number needs to be a properly formatted number. The error message is misleading.

https://support.twilio.com/hc/en-us/articles/223133967-Change-the-From-number-or-Sender-ID-for-Sending-SMS-Messages

**Comment by childish-sambino** [comment]
Ah, didn't know alphanumeric senders was a thing ([support doc](https://support.twilio.com/hc/en-us/articles/223181348-Getting-Started-with-Alphanumeric-Sender-ID-for-Twilio-Programmable-SMS)).

Since this is not related to the PHP helper lib, best to [file a support ticket](https://twilio.com/help/contact) to further debug this issue.
