### ISSUE TITLE
The "Deactivated Phone Numbers" API call is returning a 307 response causing an "Unable to fetch record" exception to be thrown

### ISSUE THREAD

**Issue by nickturrietta** [twilio/twilio-php#655]
The example PHP code for Deactivated Phone Numbers displayed on https://www.twilio.com/docs/sms/deactivated-phone-numbers returns a 307 status code, which causes an Exception to be thrown by this code in the fetch method in src\Twilio\Version.php:

```PHP
if ($response->getStatusCode() < 200 || $response->getStatusCode() >= 300) {
    throw $this->exception($response, 'Unable to fetch record');
}
```

**Comment by childish-sambino** [comment]
Similar to https://github.com/twilio/twilio-csharp/issues/534

This issue has been added to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by jdavidbakr** [comment]
Twilio sent out a pretty urgent sounding message that we need to implement this ASAP, but since their API doesn't work then those of us using the PHP API can't actually implement it.  Unless their language was exaggerated, I think fixing this issue should be a super high priority on their list, especially since there's been a pull request waiting for 3 days.

**Comment by childish-sambino** [comment]
@jdavidbakr The PR is being actively tracked and updated.
