### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by redwardh** [twilio/twilio-php#673]
Original title: Installation failing via composer (2.0.8) in PHP 8.0. Notice is [ErrorException] Undefined array key "process".

**Comment by thinkingserious** [comment]
Hello @redwardh,

Thank you for taking the time to report this!

We currently do not support PHP 8, and while it's in our backlog, we don't have a time frame for support just yet. I suggest you [subscribe to our releases](https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/viewing-your-subscriptions) to make sure you are notified when we do support PHP 8.

Pull requests and +1s on the issue summary will help it move up the backlog. I'm going to modify the title to make it clearer that this issue is related to PHP 8 support.

Thank you!

Internal tracking: DI-858

**Comment by redwardh** [comment]
Resolved the problem myself. After running composer diagnose command, I discovered the php.ini file was disabling the proc_open function, causing the installation to fail.
